### ISSUE TITLE
Tracking participation

### ISSUE THREAD

**Issue by stephwright** [stephwright/mozstuff#2]
- [x] Create XLS of minigrants applicants from round 1 and 2
- [x] Add participants / wranglers / site hosts / project leads from Global Sprints (get from Ti.to)
- [ ] Create xls of sponsorship opportunities
- [x] Inlcude WOW / OLTS participants 
- [ ] Add participants from Intro to GitHub
- [x] Add community call participants
- [x] Add Study Group leads
- [x] Add fellowship applicants
- [x] Add MozFest participants
  - [x] Check w/ Erika / Sarah re: which tabs / years in which spreadsheet

**Comment by stephwright** [comment]
https://docs.google.com/spreadsheets/d/15SRWFBhVyxzJXWryRcHhyUr10rUFZZbiKPJIslVwyO0/edit#gid=0
