### ISSUE TITLE
CHECKLIST: NYC 3/4-9/2018

### ISSUE THREAD

**Issue by stephwright** [stephwright/mozstuff#20]
- [x] Plane
- [x] Lodging
- [x] Gr Transport
- [x] Set up mtgs w/ local community members
- [x] Registration
- [x] Currency Exchange
- [x] Travel docs
- [x] Reimbursement

**Comment by stephwright** [comment]
Also arranged for flight and bus to get to/from DC in the middle of this trip

**Comment by stephwright** [comment]
Meetings:
- [x] 3/6 with Daira for planning Impact Eval mtg
- [x] 3/6 w/ Daira, Sloan, Siegel & Helmsley for Impact Evaluation of Science programs
- [x] 3/6 Social hr w/ funders 
- [x] 3/6 State of Open Data for NYC Open Data Week hosted by Siegel
- [x] 3/7 Breakfast for Siegel grantees w/ Siegel & Nick Shockey
- [x] 3/7 w/ IREX & Christine Prefontaine in DC
- [x] 3/7 w/ Eric Reese from JHU re: open data training
- [x] 3/8 w/ Meghan and Adrienne Schmoeker re: NYC Open Data Week and future collabs
- [x] 3/8 Impact of Open Data for Open Data Week
- [x] Nick Shockey to discuss collabs w/ SPARC
- [x] Dinner/drinks/coffee w/ David Riordan and Zelda?

**Comment by stephwright** [comment]
https://docs.google.com/document/d/1FdfvNUgoBArNzv7l8lFjxuRgKDyR0zPLJ_C-6xHzSUs/edit#
