### ISSUE TITLE
To Do List Feb 26 - Mar 2

### ISSUE THREAD

**Issue by stephwright** [stephwright/mozstuff#9]
- [x] set up check-in w/ Carpentries on transfer of Study Groups (#19 )
- [x] write up email to Study Group leads about transition to Carpentries (#19)
- [x] send check-in update info to Heather @ SPARC
  - [x] Virtual intro to Heather and IREX
  - [x] Send Global Sprint training & info sites
- [x] set up meeting w/ Nick in NY
- [x] set up mtg w/ Eric in DC
- [x] send info to Daira
  - [x] language for funding support from Helmsley & logo
  - [x] Names and organizations of invitees
- [x] prep for mtg w/ Fellows Team (#8)
- [x] create Community Call workflow doc for Danielle (#15 )
- [x] publicize next Community Call
- [x] Review Sloan funding
  - [x] MozRetreat
  - [x] GS Swag
- [x] flesh out community participation DB #2 
  - [x] add Study Groups
- [x] Sarah mtg agenda
  - [x] Abby WOWs w/ OLTS?
  - [x] new repo
